/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const QuestionsIndexLazyImport = createFileRoute('/questions/')()
const QuestionsAddLazyImport = createFileRoute('/questions/add')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const QuestionsIndexLazyRoute = QuestionsIndexLazyImport.update({
  path: '/questions/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/questions/index.lazy').then((d) => d.Route),
)

const QuestionsAddLazyRoute = QuestionsAddLazyImport.update({
  path: '/questions/add',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/questions/add.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/questions/add': {
      preLoaderRoute: typeof QuestionsAddLazyImport
      parentRoute: typeof rootRoute
    }
    '/questions/': {
      preLoaderRoute: typeof QuestionsIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  QuestionsAddLazyRoute,
  QuestionsIndexLazyRoute,
])

/* prettier-ignore-end */
